"""Vacation

Revision ID: dedeabe4273e
Revises: 27bf2aa3b8c7
Create Date: 2023-03-06 14:02:30.677320

"""
from alembic import op
import sqlalchemy as sa

from app.model.base import CustomUUID

# revision identifiers, used by Alembic.
revision = 'dedeabe4273e'
down_revision = '27bf2aa3b8c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacation',
    sa.Column('id', CustomUUID(as_uuid=True), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('vacation_type', sa.String(), nullable=True),
    sa.Column('employee_id', CustomUUID(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacation_id'), 'vacation', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacation_id'), table_name='vacation')
    op.drop_table('vacation')
    # ### end Alembic commands ###
